### ISSUE TITLE
Current time is not occluded by on-hover examples

### ISSUE THREAD

**Issue by outofculture** [jmstfv/rectangles#1]
Here's a screenshot:

![rectangles-bug](https://user-images.githubusercontent.com/28812/162805238-cffba4a1-fc80-46fc-99e0-2460e4e26d86.png)

It only affects the current, partially-filled rectangle. This is in firefox. Do you need any other details?

**Comment by jmstfv** [comment]
@outofculture thanks for flagging this!

I'm aware of this bug. Tried fixing it in the past but couldn't find a solution, so left it as is for now.

**Comment by jmstfv** [comment]
fixed in #2
